### ISSUE TITLE
FastDeepEqual used in victory-core 21.1.5 causing RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yizhoucao** [FormidableLabs/victory#964]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I encountered this issue for a VictoryPie using a VictoryTooltip as its labelComponent. If no react component is supplied to the labelComponent prop, this error wont occur. It is caused by the FastDeepEqual package introduced in victory-core 21.1.5 because if I install victory-core 21.1.4, this issue wont occur. 

In this issue https://github.com/epoberezkin/fast-deep-equal/issues/8, it is indicated that this package is ignoring the possibility of a circular object being tested for equality. We all know react component are circular structure and this could cause a infinite loop of equality check.

Strangely I only encounter this issue on my windows 10 PC while mac is working fine.

**Comment by chrisbolin** [comment]
@boygirl yes!

**Comment by chrisbolin** [comment]
@yizhoucao thanks for reporting this! Your initial debugging steps were helpful. I'll keep you posted on our progress :)

**Comment by chrisbolin** [comment]
just some quick benchmarking: 
in chrome debugger with _4x CPU slowdown_ on 15" MBP circa 2016, each fast-deep-equal call stack error only takes *73ms in total*. This appears to be actually less severe than I thought. Will continue to dig and get to the root cause.

**Comment by chrisbolin** [comment]
![image](https://user-images.githubusercontent.com/2822048/38530686-238dd5ca-3c29-11e8-9be2-e667b22d8c84.png)

**Comment by yizhoucao** [comment]
Thanks @chrisbolin. Adding the try catch is works for us 👍

**Comment by chrisbolin** [comment]
believe I've found the root cause. should have a fixed version of `victory-core` (that _does not_ have to hit catch a `RangeError`) tomorrow 🎉

**Comment by chrisbolin** [comment]
## Root Cause: React Elements

The crux of the issue here is that React _elements_ (not react components) contain circular references if they were instantiated in another React element. The simple test for this is that they have a non-null `._owner` field. Deeply inside of this field is a reference to the initial element (`element._owner.return.stateNode.current.child`).

#### Circular

- created inside a react class: render, constructor, initial state, default props, etc.
- created inside a functional component (that is then rendered).

#### Non-circular

- created anywhere else: globally, inside a function, inside a non-Component class.

The only reason we weren't hitting this a lot is because usually the label is the _same element reference_: it is a default prop and never changes and is therefore strictly equal to itself. `const a = <SomeElement/>; const b = a; // a === b;`

I tested both React 16 (Fiber) and 15 (pre-Fiber), and the behavior (down to the exact `_owner` property) is the same; therefore our solutions can handle both.

_I have a few solutions in mind and will write them up next._

**Comment by chrisbolin** [comment]
## Suggested changes to `areVictoryPropsEqual(a, b)`

For each of the props in `a`...
- if it is an object with non-null `._owner`
  - if the same reference on `b` (strict compare to `b[sameKey]`) continue
  - else
    - _open discussion. see below_
- else, use `fast-deep-equal`
  - if `false`, return `false` early
  - if `true`, continue
  - catch any errors with `fast-deep-equal`
    - if caught, warn the user (this is for non-React circular references. we'll want to change the wording), and return `false`
- return `true` (as no early false returns have been hit)

### What if we have non-equal React Elements?

We can two choices...

**A.** Skip comparing them and treat them as equal. This is what we do with functions currently, and it's good for performance. Edge cases could be handled the same way functions are treated: the dependecies are passes as props so they are checked and cause rerenders when they change.

**B.** Treat them as unequal. This is will cause a lot more re-renders, but maybe we safer.

I am highly in favor of **A**.

**Comment by ryan-roemer** [comment]
@chrisbolin -- It may be worth investigating how lodash detects and handles circular references in their deep equal.

**Comment by chrisbolin** [comment]
@ryan-roemer done :)

It's likely one of the reasons `lodash.isEqual` is [**8 times slower**](https://github.com/epoberezkin/fast-deep-equal#performance-benchmark) than fast-deep-equals: _it caches traversed objects in order to compare them_.

**Comment by chrisbolin** [comment]
https://github.com/lodash/lodash/blob/master/.internal/baseIsEqualDeep.js#L22

**Comment by chrisbolin** [comment]
hey @Lelith! the `victory-core@21.1.6` patch should let you move on. And we should have another patch soon that is even more performant.

**Comment by chrisbolin** [comment]
@yizhoucao and @Lelith, `victory-core@21.1.8` is out now. this should fix the issues you saw, and not even throw a warning in the console. let us know if that does not work

**Comment by ecnaidar** [comment]
@boygirl 
I have encountered 
```react-fast-compare does not handle circular references. RangeError Maximum call stack size exceeded``` in same scenario although while using VictoryScatter.
Thought that it might be some regression during recent restructure (first tried on victory 31.0.0) but after reading this thread I tried version that uses victory-core version closest to when this fix was released (`victory: 0.26.0, victory-core: 22.0.0`) and the issue was still present.
The warning appears **only in production build** and seems to go away if `labelComponent` prop is not provided.

**Comment by chrisbolin** [comment]
Thanks for reporting this! It might help us track down a bug that has been
difficult for us to reproduce. Could you tell us about your build system?
Webpack, uglify, terser, etc?

**Comment by chrisbolin** [comment]
@ecnaidar to expound on that— the best thing I could get would be a full repository that would reproduce the issue. You could just start with what you have and cut out everything. Or you could start with some boilerplate and try to reproduce it. e.g. https://github.com/chrisbolin/react-fast-compare-bug-reproductions/tree/issue-30-circ-ref-cra 

I've been tracking the issue in https://github.com/FormidableLabs/react-fast-compare/issues/30 by so far i personally haven't reproduced it, so code to do that would be *awesome*!

**Comment by chrisbolin** [comment]
using FormidableLabs/react-fast-compare#30 to track @ecnaidar's issue, as it is with `react-fast-compare` and not `fast-deep-equal` (as this issue #964 was opened for)
